name: Publish

on:
  [workflow_dispatch]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Trader.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.x
            
    - name: Remove Database Projects
      run: |
        dotnet sln remove Trader.Data.Sql.Database/Trader.Data.Sql.Database.sqlproj
        dotnet sln remove Trader.Orleans.Database/Trader.Orleans.Database.sqlproj
        rm -f -d -r Trader.Data.Sql.Database
        rm -f -d -r Trader.Orleans.Database
              
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE_PATH }} --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
      
    - name: Publish
      run: dotnet publish ${{ env.SOLUTION_FILE_PATH }} --no-build --configuration ${{ env.BUILD_CONFIGURATION }}

    - name: Publish NuGet Trader.Core.Abstractions
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./Trader.Core.Abstractions/Trader.Core.Abstractions.csproj
        PACKAGE_NAME: Outcompute.Trader.Core.Abstractions
        VERSION_FILE_PATH: Directory.Build.props
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
